### ISSUE TITLE
[Question] Multithreaded producer - how to handle order delivery order?

### ISSUE THREAD

**Issue by nbalsamo** [phobos/phobos#100]
Background: we have a producer process that is multi threaded (think Sidkiq with a concurrency of 5). Recently, we noticed that messages sent to the same partition will be out order since they were produced on different threads, and thus different producers. 

While this makes sense to me, I was wondering if you have an recommendations for this order problem. We were thinking about forcing each thread to use the same producer but were unsure of the repercussions.

**Comment by klippx** [comment]
I assume order matters for you and your concern is regarding message ordering of events of a particular instance of a business object (aggregate).

So for an aggregate let's say the following operations happens in this sequence `[op1, op2, op3]` but these events happen in 3 separate threads, did I get that right?

But the threads might finish in any order e.g. `[op3, op1, op2]`, and that is what the kafka cluster will receive and that will be the log for what happened to the aggregate. 

Kafka actually cares about the order the message comes. So in this case it won't matter if you assign each thread to it's own producer, it is _when_ the message reaches kafka that is relevant, kafka will put it in a partition based on your partition key and in this case it will be `[op3, op1, op2]` for this aggregate.

If you actually need the order to be correct in kafka logs, you have to do some kind of synchronization. It sounds like you are in control of how to split the jobs between producer processes. 
- So, I would suggest you investigate if you can divide work about a certain aggregate to dedicated processes (e.g. partitioned in a similar way that kafka should partition). This should ensure that events are treated in order by your system, and by that also messages arrive to kafka in the correct order.

The scenario I imagine you have is that you just throw work out like this in a work queue:
- `job1 = [aggregate_id, 'op1']`
- `job2 = [aggregate_id, 'op2']`
- `job3 = [aggregate_id, 'op3']`

And then your processes just grabs these in a multithreaded way:
- `[process1(job1), process2(job2), process3(job3)].join`
and that is why they finish/produce to kafka in random order. It is exactly that you have to try to avoid. 

Instead aim for this:
- `process1(job1)`
- and then `process1(job2)`
- and then `process1(job3)`

Dont get me wrong, keep the multithreading. But make sure `process2` and `process3` work on completely different aggregate ids. Get the partitioning sorted :)
