### ISSUE TITLE
Phobos not consuming from remote machine

### ISSUE THREAD

**Issue by singhmehtab571** [phobos/phobos#107]
I have setup Phobos in my rails application. when I produce data from the same machine on a particular topic and start Phobos, data goes to the handler and is processed. But when I start Phobos with remote listeners, it says connection timed out or failed to connect.

**Comment by mensfeld** [comment]
It doesn't seem like a phobos problem but rather problem with your setup / networking. Please provide more details and logs.

**Comment by singhmehtab571** [comment]
when I enter localhost as producer ip and on a particular topic i produce a message.
phobos consumes it.
when a message is produced on a different ip on a remote machine or a local machine for a particular topic, Phobos shows failed to connect to that ip or connection timed out.
but that ip is working properly as i have checked by producing data from a remote machine and consuming it with the help of simple Kafka consumer command.
only through Phobos, i am not able to consume it.

**Comment by mensfeld** [comment]
You still didn't provide any logs. It still does sound like a connection problem. Did you try telneting to your remote kafka?

**Comment by singhmehtab571** [comment]
<img width="1436" alt="screen shot 2019-02-21 at 6 13 27 pm" src="https://user-images.githubusercontent.com/46445404/53170260-b7544380-3605-11e9-976f-312e842dc202.png">

**Comment by singhmehtab571** [comment]
you can see the logs.
the connection with ip is fine as i am able to consume messages with the help of simple kafka consume command.
the only problem is with the help of phobos

**Comment by klippx** [comment]
Both phobos and ruby-kafka are working (can connect to kafka broker) for everyone else, this is probably due to some specific problem in your network that you need to find and fix. It is could be anything from firewall to wrong ports etc. 

I would suggest to do a more thorough investigation with your network guys, maybe try to connect using kafkacat or some other tool from your machine to rule out environment issues. 

If that works, try opening a console and connect using ruby-kafka library directly to prove that works.

And if that works, then Phobos should also work.

**Comment by singhmehtab571** [comment]
ruby-kafka version is 0.5.5

**Comment by singhmehtab571** [comment]
bin/kafka-console-consumer.sh --bootstrap-server a.b.c.d:9092 --topic test 
using this command i am able to consume what ever is being produced from remote machine with a.b.c.d being the ip on which data is produced.
and also i am able to properly connect to that ip address.
Only through phobos i am not able to consume. Maybe there is a compatibility issue with ruby kafka and phobos

**Comment by klippx** [comment]
Try this:

```
> bin/console # or rake console, or irb
$ require 'ruby-kafka'
$ kafka = Kafka.new(["a.b.c.d:9092"], client_id: "my-application")
$ kafka.each_message(topic: "test") { |m| puts m.value } 
```

Does this work? This is not a script and you might need to change something, it's pseudo code to test kafka connection via ruby client.

**Comment by singhmehtab571** [comment]
yeah, there is compatibility issue...ruby-kafka is not able to make the connection.
my rails version is 4.2.4

**Comment by mensfeld** [comment]
I would rather ask what is the Kafka version. They may mismatch with ruby-kafka.

**Comment by klippx** [comment]
You should have Kafka <= 0.10 if you are using ruby-kafka 0.5.x: https://github.com/zendesk/ruby-kafka#compatibility

But you can upgrade to 0.7.x and run Kafka 0.10.

I bet you are running Kakfa 1.x or even Kakfa 2.x...?

**Comment by dorner** [comment]
Going to assume this was fixed or is no longer relevant.
