### ISSUE TITLE
phobos on jruby

### ISSUE THREAD

**Issue by sdahlbac** [phobos/phobos#109]
I'm trying to run phobos on jruby (due to bits in the handler needing JRuby), but it seems that the phobos gem unconditionally depends on concurrent-ruby-ext?

https://github.com/phobos/phobos/blob/master/phobos.gemspec#L63

**Comment by klippx** [comment]
There is an easy fix: https://engineering.klarna.com/creating-a-rubygem-compatible-with-ruby-and-jruby-559161bfea2d

Try wrapping the gemspec like this:

```
  if RUBY_PLATFORM !~ /java/
    spec.add_dependency 'concurrent-ruby-ext', '>= 1.0.2'
  end
```

It only contains optimizations for MRI using C extensions, you will be missing out on those optimizations that's all.

**Comment by sdahlbac** [comment]
I did a fork and at least it installs after that change, but not sure if we want to be the pioneers running jruby+phobos (with regards to any potential rough edges and bleeding) so it may still be we end up changing other bits to be able to use MRI.

Still, if you want that PR anyway I can submit it.

**Comment by klippx** [comment]
I think the PR would be OK to have, but I guess it won't do much unless we also test that it actually works, so I think we should make sure it runs on jruby though by adding jruby to CI: https://docs.travis-ci.com/user/languages/ruby/#jruby-testing-against-multiple-jdks

If you want to be pioneers, you can definately try it 🐸

**Comment by lukluk** [comment]
why not creating java class Kafka consumer and use it on JRUBY? instad of bleeding to force this gem work on Jruby

**Comment by mensfeld** [comment]
Exactly as @lukluk said. Java Kafka consumer is better than ruby-kafka or librdkafka.
