### ISSUE TITLE
Support for message headers

### ISSUE THREAD

**Issue by cassiomarques** [phobos/phobos#114]
Hello! 

I was reading through the code and could not find anything related to message headers. I believe `ruby-kafka` supports them, is that something that Phobos supports as well? In our project we need the ability to add stuff to a message header when publishing and also retrieve information from headers when consuming.

Thanks for such a good library!

**Comment by dorner** [comment]
Not right now we don't - feel free to open a PR!

**Comment by cassiomarques** [comment]
I'll have a go at that :-)

**Comment by cassiomarques** [comment]
This has now been added by https://github.com/phobos/phobos/pull/115
