### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by Pash-tet** [phobos/phobos#123]
Hello, i try to create a producer as written in the documentation.
```
class TestProducer
  include Phobos::Producer
end
```
Then i call it
`TestProducer.producer.publish(topic: 'test', payload: {test: 'test'}.to_json)`
I catch error
`ArgumentError (wrong number of arguments (given 1, expected 2..4))`

Phobos running standalone.
Gem version 1.8.2, ruby version 2.6.3, rails version 6.0.2.1

**Comment by dorner** [comment]
@Pash-tet please try with the latest version, 1.9.0-beta3. It's still technically in beta because we haven't had anyone use it on production yet, although that should change very soon!

**Comment by Pash-tet** [comment]
@dorner I can't install this version:
```
gem install phobos -v '~> 1.9.0.pre.beta2'
Successfully installed phobos-1.9.0.pre.beta3
Parsing documentation for phobos-1.9.0.pre.beta3
Installing ri documentation for phobos-1.9.0.pre.beta3
Done installing documentation for phobos after 0 seconds
1 gem installed
```

Only phobos-1.9.0.pre.beta3, in this version i have another error:

```
TestProducer.producer.publish(topic: 'test', payload: 'test')
NoMethodError (undefined method `producer_hash' for nil:NilClass)
```

**Comment by dorner** [comment]
Can you post the full backtrace?

**Comment by dorner** [comment]
Maybe you forgot to call `Phobos.configure`?

**Comment by Pash-tet** [comment]
Yes, I forgot to add this line to initializer. Everything worked. Thanks for the help. Good luck with the release. I want to use this gem in production.
