### ISSUE TITLE
A new listener is started when opening Rails console

### ISSUE THREAD

**Issue by luizvarela** [phobos/phobos#124]
Hello folks, I've been using Phobos as a producer and it works really well in production. But now we started to introduce consumers, the thing is, every time we open a new rails console the instance of the server tries to start a new listener.

we have an initializer file with something like this:

```
Phobos.configure('config/phobos.yml')
Phobos::Executor.new.start
```

and we get this when opening a rails c:

```
Phobos : <Hash> {:message=>"Phobos configured", :env=>"..."}
Phobos : <Hash> {:message=>"Listener started", :listener_id=>"...", :group_id=>"...", :topic=>"...", :handler=>"..."}

pry(main)> ERROR -- RubyKafka : Timed out while waiting for response 1
ERROR -- RubyKafka : Connection error while trying to join group `...`; retrying...
```

I guess this is because we start it in the initializer, but I'm not sure what's the best approach. Do you have any advice  to handle this?

**Comment by dorner** [comment]
Yep, the initializer is definitely not the right place to do this. In Deimos (https://github.com/flipp-oss/deimos/) we created a Rake task to start it. You can check out the implementation here:
https://github.com/flipp-oss/deimos/blob/master/lib/tasks/deimos.rake

**Comment by luizvarela** [comment]
Thanks @dorner, that seems the best way. I'm gonna check this out. 🙌
