### ISSUE TITLE
Enable persistent connection caused MessageSizeTooLarge error

### ISSUE THREAD

**Issue by renjiexu** [phobos/phobos#128]
Hi phobos team,

Recently we adopted persistent connection for our consumers (we do publish inside the consumer), and we notice one of the handlers raising MessageSizeTooLarge issue, but the payload size is small (< 10kb), we have 1MB limit (default) in broker.

For this specific handler, it has:
max_concurrency: 1
~delivery_interval: 100~   =>  **offset_commit_interval: 100**
~delivery_threshold: 3~   =>  **offset_commit_threshold: 3**
Traffic is around 100/second

Do you see any reason could cause this? I read the code and phobos does publish + deliver_message per each message, so not sure how it could happen, any thoughts would be helpful. Thanks!

**Comment by dorner** [comment]
MessageSizeTooLarge is a bit misleading. It happens if the message *batch* is too large.

Phobos does a "publish", but that passes the code down to RubyKafka, which uses settings to decide on what to do with it. If your `delivery_threshold` or `delivery_interval` aren't set up correctly, you might be trying to publish a batch which is too large.

**Comment by renjiexu** [comment]
@dorner thanks! sorry I was misleading in my description, since we're using sync + persistent connection, those delivery_internal/threshold are not used if I understand correct. Does sync publish still do batch?

**Comment by dorner** [comment]
Yes, it does - but it goes into a queue for deliver_messages and I forgot that Phobos calls deliver_messages immediately for sync. The only thing I can think of is that you're passing a *list* of messages to the `publish_list` method and that list is greater than the limit?

**Comment by renjiexu** [comment]
> The only thing I can think of is that you're passing a list of messages to the publish_list method and that list is greater than the limit?

Right, that's the case I saw as well but we do publish per message, that's why I'm very lost 😵

**Comment by dorner** [comment]
I'm out of ideas. 🤷‍♂️ Maybe try asking on the RubyKafka slack / GitHub?

**Comment by renjiexu** [comment]
thanks for your help, will poke around and update the ticket if I found anything

**Comment by renjiexu** [comment]
Hi @dorner , we found the issue, assuming we have two messages:
1. size: 2MB
2. size: 10kb

By sending the first one, it would result in MessageSizeTooLarge and kept that in `buffer` of producer, then publishing the second message will flush both of them out which still MessageSizeTooLarge.

I think this could be fixed on either ruby-kafka or phobos side (if phobos, we could just shutdown the sync_producer if the exception is `MessageSizeTooLarge` even it's persistent connection). What do you think?

**Comment by renjiexu** [comment]
I found this discussion: https://github.com/zendesk/ruby-kafka/issues/567, I guess your opinion is to fix this on ruby-kafka side 😃

**Comment by dorner** [comment]
Ah, so you found that bug. :) Yes, this has to be fixed on the RubyKafka side.

**Comment by renjiexu** [comment]
Make sense, close now and will address in ruby-kafka side.
