### ISSUE TITLE
Support rdkafka-ruby implementation

### ISSUE THREAD

**Issue by cjford** [phobos/phobos#132]
Based on this slack exchange from a few months ago, it sounds like the maintainers of ruby-kafka are recommending to use [rdkafka-ruby](https://github.com/appsignal/rdkafka-ruby), as ruby-kafka will not be actively developing support for new kafka features going forward.

<img width="354" alt="Screen Shot 2020-12-03 at 12 40 44 PM" src="https://user-images.githubusercontent.com/1410645/101079509-d024b380-3564-11eb-9e1b-e4b9bcf39fcf.png">

I was curious what the phobos team's take on this is. Obviously porting phobos over to a different library would be a large undertaking, is it something that's been considered? Maybe there are other options too, like adapters for a configurable backend. Is there any interest or ongoing work on this?

Our team would be interested in contributing to this effort, if there is one. We use phobos across a large codebase, and helping to support future kafka versions in phobos is preferable to migrating to something else like racecar, or making a fork of phobos.

**Comment by dorner** [comment]
I definitely understand the ruby-kafka team's frustration here. I think long-term we likely won't have much of a choice. Having said that, I've had some frustrations with rdkafka in different languages (particularly Node) and being able to debug things in pure Ruby is also a huge plus in my opinion.

In general, there are still many things that ruby-kafka supports that ruby-rdkafka doesn't yet, largely around instrumentation and being able to hook into the process at different intervals, and there seems to be a) less work and contribution around ruby-rdkafka and b) a higher incidence of bugs and missing features. It just doesn't seem to quite be there yet.

Having said that, I'm definitely not opposed to a new version of Phobos that supports rdkafka-ruby. However, the Phobos code is small enough and tightly enough coupled to ruby-kafka that I almost think we'd need a brand new phobos-rdkafka gem which matches the same API as Phobos but whose underpinnings are different. We could look at what we could extract which is common functionality, but my hunch is that we'd end up with less than half of the codebase that could actually be reused.

**Comment by mensfeld** [comment]
I can add a couple of things here as well as I'm actively working on moving to rdkafka. As @dorner said, it lacks many things atm and some things need heavy improvements (like callbacks that are done with the global state).

Many things run differently with rdkafka and porting is not just changing underlying code but actually reworking many corner cases, potential memory leaks, and other things. 

That said I anyhow wish you luck and whenever needed you can count on me for additional help ;)

**Comment by dorner** [comment]
I'm not really sure whether the chicken or the egg would come first here - if the work should be focused on rdkafka-ruby to fix it up and make it easier to write higher-level gems on top of it, or if the higher-level gems should come first and contribute back to rdkafka-ruby. -_- 

At our company, we rarely use more than the main Kafka features that haven't changed in ages (producers/consumers) so we don't have a strong impetus to switch.

**Comment by cjford** [comment]
@dorner @mensfeld Thanks for your input, and good points about maturity of rdkafka. I would say prioritizing improving rdkafka-ruby might help prevent some fragmentation/effort duplication of higher-level gems. But in this specific case it might not matter much, since the main point of the theoretical "phobos-rdkafka" gem would be to provide the phobos interface and thus splitting from efforts of e.g. racecar is inevitable.

@mensfeld I'm curious what your work moving to rdkafka looks like now. Are you referring to porting the karafka project off of ruby-kafka?

**Comment by mensfeld** [comment]
@cjford yes. We are migrating to rdkafka, though rdkafka is just one of the things related to karafka 2.0. As @dorner said, rdkafka has it's own problems. You can look at waterdrop 2.0 (producer wrapper around rdkafka to see how many things had to be done to mitigate some of the problems).

**Comment by cjford** [comment]
I suppose we can mark this closed now. 

To summarize: it sounds like an effort to port phobos as it exists is not very plausible without being closer to a rewrite. A separate/new version of phobos is an option, but limited by the maturity of rdkafka. In the meantime, those interested in using rdkafka may want to look into karafka/waterdrop, and consider contributing to rdkafka itself.

Thanks for chiming in, feel free to continue discussion and post any relevant updates.
