### ISSUE TITLE
How to force the consumers to stop?

### ISSUE THREAD

**Issue by mbarany** [phobos/phobos#133]
I looked around but didn't see any obvious way to forcibly stop the consumers. I'm using Rails and once in a while the Database will get disconnected and what ends up happening is that it waits 5 seconds for a connection, then fails and raises which causes phobos to retry it a few times and then eventually skips over the message. I'd rather it stop if possible and maybe send a kill signal to the container it's running in which would just spin up a new container and pickup where it left off. thanks in advance for your response!

**Comment by dorner** [comment]
Hey - yep, the best way to force Phobos to stop is indeed to send a SIGINT to the process. There isn't really a way to do it from outside of the code.

**Comment by dorner** [comment]
Although btw the default is not for it to skip over any messages and to essentially retry forever. If that's the behavior you're seeing there may be a configuration issue.

**Comment by mbarany** [comment]
thanks for the quick response! yes, it appears that I am skipping over it when encountering an issue after X retries.

**Comment by dorner** [comment]
Yeah I don't think Phobos will do that itself. The only way you'd skip messages would be if at some point the error went away and you successfully consumed it and committed your offset. Phobos won't do that for you.
