### ISSUE TITLE
Force phobos to only listen to a fixed set of partitions (e.g. 4 out of 12)

### ISSUE THREAD

**Issue by ayqazi** [phobos/phobos#134]
Hi,

I wish to spread my consumer amongst multiple hosts. Say my topic has 12 partitions, then I want VM1 to consume from 4 of those, VM2 to consume from the next 4, and VM3 to consume from the last 4.

Yet when I start a phobos consumer processes against a topic with multiple partitions, it grabs all of them.

Is there a way to granularly configure Phobos to consume only from a subset of the partitions of a topic?

**Comment by dorner** [comment]
Um... that's not really how consumers usually work. Typically each consumer starts up and tries to grab all the partitions. As more consumers come online, the partitions get rebalanced until each consumer will end up with (# partitions / # consumers) partitions. As long as you specify the same consumer group ID for all of them, this should happen transparently. It may take a couple of minutes for the rebalancing to sort itself out (depending on your timeout and session values), but after that you should be golden. 

This has the advantage of automatically rebalancing if you want to add more consumers or if one of them goes down.

Is there a reason this workflow doesn't work for you?

**Comment by ayqazi** [comment]
Ah....... lightbulb moment. Thank you. I was previously playing with the max_concurrency setting of the listener and was having problems with parallelization, and misunderstood the issue.
