### ISSUE TITLE
Cannot find ActiveRecord Class in Rails 6

### ISSUE THREAD

**Issue by cdesch** [phobos/phobos#137]
I have phobos configured with in the rails `initializers/phobos.rb` to start an `executor` from the `config/phobos.yml` like the the following:

    Phobos.configure('config/phobos.yml')
    executor = Phobos::Executor.new
    executor.start

I get a ` :exception_class=>"NameError", :exception_message=>"uninitialized constant TransactionsConsumer::Address"` error when trying to load the `Address` model from `ActiveRecord`. There should be no `TransactionsConsumer::Address` but it should find the `Address` class in `app/models/address.rb`.

My Consumer in `app/consumers/transactions_consumer.rb`:
    
    class TransactionsConsumer
      include Phobos::Handler
    
      def self.start(kafka_client)
        # setup handler
        puts "Starting Transaction Consumer"
      end
    
      def consume(payload, metadata)
        puts metadata
        puts payload
        data = JSON.parse(payload)
        if Address.exists?(address: data["fromAddress"])
          AccountBalanceUpdateJob.perform_in(1, data["fromAddress"])
        end
      end
    end

I assume I'm not configuring Phobos correctly in some way to autoload or see the Rails Classes. How do I get Phobos configured to work with Rails models/objects?

**Comment by dorner** [comment]
Hey - so this seems to indicate that you don't have Rails autoloading working. :) You need to use the `phobos_boot.rb` file (which should be in your root directory) to load Rails. It should be as simple as replacing the contents of that file with

`require_relative 'config/environment'`

**Comment by cdesch** [comment]
This issue was my own silly mistake. I renamed `Address` class to `Account` and thought it was the way Phobos was loading the whole project. Thank you for looking at it!

**Comment by dorner** [comment]
Thanks for following up!
