### ISSUE TITLE
Heartbeats in a separate thread

### ISSUE THREAD

**Issue by ivanRylach** [phobos/phobos#142]
Hello folks!

Huge thank you for your work on this project!

Recently, we ran into the limitation of heartbeats not being sent from a separate thread, while working with `delivery: message`. I understand that this is a limitation of `ruby-kafka` and discovered this PR https://github.com/zendesk/ruby-kafka/pull/619, where @dorner attempted to isolate heartbeats from message processing. Unfortunately, it looks like PR was closed due to inactivity.

Could you provide more details whether it worked for you? If not, do you have any recommendations, on how can we mitigate this issue with `phobos` only?

Thank you!

**Comment by dorner** [comment]
Hi @ivanRylach. Unfortunately we abandoned the approach because it was a lot more complex than it looked. The fix ended up being this instead: https://github.com/phobos/phobos/commit/cfb73ec0266dbbf8f454831daa97e273b4df019a

Are you using the latest version of Phobos? It should be sending heartbeats after every message when using `delivery: message`.

**Comment by ivanRylach** [comment]
@dorner Thank you! Yeah, we are running the version, which sends heartbeats after each message, but due to some other complications it takes a while to process them. We increased `session_timeout` as a short term mitigation, but would like to find a way to solve it in a more general way.

**Comment by dorner** [comment]
If you're taking that long to process a single message, you might want to have code to actually send the heartbeat in the middle of processing. E.g. you have a loop and on every iteration you send the heartbeat if necessary.

Having said that, I would recommend against using a Kafka consumer as a "job processor" - I've found that especially in Ruby, it works best if your consumer is very fast. You can offload the actual job processing to a delayed job, something like Sidekiq or SQS, and I've found that pattern works a lot better than doing it inline when you have long processes.

**Comment by ivanRylach** [comment]
Got it! Thank you for the context @dorner !
