### ISSUE TITLE
LoadError in 2.1.1

### ISSUE THREAD

**Issue by macav** [phobos/phobos#150]
After updating to version 2.1.1, i'm getting `LoadError: cannot load such file -- phobos/configuration` when I try to `require 'phobos'`. 
Ruby 3.0.3.
Let me know if you need any more info.
Thanks.

**Comment by dorner** [comment]
@macav thanks for the heads up! This has been fixed. It was a packaging error before pushing the gem. :(

**Comment by dorner** [comment]
Please update again to 2.1.2.
