### ISSUE TITLE
Feature request: allow regexp tags in phobos.yml

### ISSUE THREAD

**Issue by lukewestby** [phobos/phobos#153]
Hi folks,

Would you consider a PR to allow for the use of regexp tags in the configuration YAML file?

Specifically, this array and the corresponding one in the backward-compatible call below it could be modified to include `Regexp`.
https://github.com/phobos/phobos/blob/master/lib/phobos/configuration.rb#L45

This would allow users to take advantage of pass-through behavior of ruby-kafka to provide regexp topic names to listen to more than one topic, like so

```
...
listeners:
  - handler: MyHandler
    topic: !ruby/regexp /^some_prefix/
    ...
```

**Comment by dorner** [comment]
Nope, I'm not against it. Fire away!
