### ISSUE TITLE
Conflict with mfmt

### ISSUE THREAD

**Issue by laleshii** [phobos/phobos#159]
FYI since you are using the `logging` gem: https://github.com/TwP/logging/issues/242

The `logging` gem top level class name seems to be in direct conflict with the `mkmf` standard library.

```
require 'mkmf'
> Logging
=> MakeMakefile::Logging
```

**Comment by dorner** [comment]
@laleshii this would have something to do with the order that you load these gems.

```
➜  irb
2.7.0 :001 > require 'logging'
 => true 
2.7.0 :002 > Logging
 => Logging 
2.7.0 :003 > require 'mkmf'
 => true 
2.7.0 :004 > Logging
 => Logging 
2.7.0 :005 > exit
```

vs

```
➜  irb
2.7.0 :001 > require 'mkmf'
 => true 
2.7.0 :002 > Logging
 => MakeMakefile::Logging 
2.7.0 :003 > require 'logging'
 => true 
2.7.0 :004 > Logging
 => MakeMakefile::Logging 
```

This seems to be an issue with `mkmf` itself, because even trying to reference `::Logging` fails when the load happens in this order.

**Comment by laleshii** [comment]
Makes sense, I haven't gone down the rabbit hole of establishing exactly what's the culprit here.

I guess `mkmf` definitely messes with the `Logging` name, intentional or not.

**Comment by dorner** [comment]
Closing this as neither of these gems are part of phobos :)
