### ISSUE TITLE
Access kafka consumer or phobos listener in handlers so manual heartbeats can be triggered

### ISSUE THREAD

**Issue by t3h2mas** [phobos/phobos#160]
Goal: Be able to manually trigger consumer heartbeats

Proposal: Pass a reference of either the `Phobos::Listener` or the `Kafka::Consumer` along with the `kafka_client` in  `Phobos::Handler.start`

Also open to alternative ways to trigger the heartbeat if I've missed something.

Note: I'm under the assumption that the heartbeat must be from the handler/listener consumer instance in order for that consumer to not be kicked out of the group.

Happy to send a PR

**Comment by dorner** [comment]
@t3h2mas what's your use case? Phobos will heartbeat if necessary after every message, even in batch mode (although not in inline batch). Are you taking so long to process a single message that you have to heartbeat manually in the middle?

**Comment by t3h2mas** [comment]
@dorner Yes. :sigh: We are extending the kafka session timeout for now. Manually triggering a heartbeat would cut down on delays when the consumer does leave the group. (Long term we are working on reducing the processing time 🤞)


In general, the result of `create_kafka_consumer` could be valuable to handlers since phobos handles the configuration of the consumer.

**Comment by dorner** [comment]
I'm definitely open for a PR. In general if your consumer is taking a long time to process a message, I usually suggest offloading it to a job queue like Sidekiq or Delayed Job. Kafka is generally built around getting through messages quickly.

**Comment by mensfeld** [comment]
Just to be clear confluent does accept pausing as a strategy for long running jobs: https://www.confluent.io/blog/kafka-consumer-multi-threaded-messaging/

**Comment by dorner** [comment]
Yep, it's possible. It just introduces extra complexity into a workflow that I (at least) try to keep as simple as possible. I find it's usually a better tradeoff to use existing, well-supported tools to offload the work rather than trying to build long processing into a Kafka consumer.

**Comment by mensfeld** [comment]
Yeah, that was just for the record. Long-running jobs or anything that would exceed max poll interval or heartbeat interval is not easy to deal with and if can be omitted by reducing the processing time, it should.

**Comment by t3h2mas** [comment]
Clarifying question: do heartbeats get sent on retry? @dorner would you know this one?

**Comment by dorner** [comment]
Heartbeats would be sent after each message is processed. If by retry you mean that the listener crashed entirely and restarted, it wouldn't heartbeat until the message was successfully processed.

**Comment by t3h2mas** [comment]
Focusing on reducing processing time. Closing for now
