### ISSUE TITLE
Disbale Phobos on Rails Console

### ISSUE THREAD

**Issue by orubin** [phobos/phobos#163]
Hey all.

I habe phobos in my app in `config/initializers/phobos_boot.rb` - running when the app starts and listening to kafka.

When i start rails console - i see logging of phobos in the console.

Any way to not start phobos in rails console?

Thanks.

**Comment by dorner** [comment]
I've done this in the past by adding this to the top of the file:

```ruby
unless Rails.const_defined?('Console')
  # ... rest of file here
end
```

**Comment by orubin** [comment]
> I've done this in the past by adding this to the top of the file:
> 
> ```ruby
> unless Rails.const_defined?('Console')
>   # ... rest of file here
> end
> ```

Thanks @dorner
