### ISSUE TITLE
Ability to set group.initial.rebalance.delay.ms

### ISSUE THREAD

**Issue by krobitaille-stash** [phobos/phobos#166]
Looking through the configuration settings for Phobos I'm not seeing a way to set this property for an initial rebalance delay?  Is there a way i'm able to set some of these additional Kafka properties?
`group.initial.rebalance.delay.ms`

We've seen some strange connection issues since migrating to EKS and it appears it has to do with too many rebalance attempts as pods are being spun up and down.  I was hoping to explore using this setting to delay rebalances on new pods being spun up all at once.

**Comment by dorner** [comment]
@krobitaille-stash I think that's an rdkafka setting. Phobos is based on ruby-kafka which is pure Ruby. There isn't a corresponding setting for that.

In general, ruby-kafka hasn't had updates in a long time. Most Kafka + Ruby implementations seem to be migrating to [https://github.com/karafka/rdkafka-ruby](https://github.com/karafka/rdkafka-ruby) .

**Comment by krobitaille-stash** [comment]
> @krobitaille-stash I think that's an rdkafka setting. Phobos is based on ruby-kafka which is pure Ruby. There isn't a corresponding setting for that.
> 
> In general, ruby-kafka hasn't had updates in a long time. Most Kafka + Ruby implementations seem to be migrating to https://github.com/karafka/rdkafka-ruby .

Unfortunate but yeah I did see that ruby-kafka is no longer being updated.  Are there plans to integrate Phobos with rdkafka or is the advice to swap off of Phobos to pure rdkafka?

**Comment by dorner** [comment]
We'd have to rewrite Phobos entirely to support rdkafka. Which is something we are considering (in which case we'd probably fork it to a new project), but we may also just bite the bullet and move to Karafka instead. It's something that we're looking into in my company, but I'm not sure how long it'll take to get to.

**Comment by mensfeld** [comment]
Let me chime in if you don't mind @dorner as the maintainer of those interesting tools ;) (karafka, waterdrop, rdkafka-ruby, etc)

This setting is **not** a librdkafka or karafka setting. The `group.initial.rebalance.delay.ms` is a broker setting and can be set whether it is rdkafka or ruby-kafka.

Taken from Kafka docs:

> The amount of time the group coordinator will wait for more consumers to join a new group before performing the first rebalance. A longer delay means potentially fewer rebalances but increases the time until processing begins.

It is possible to simulate this at least in Karafka via deferring the connection lister start; however, it would have to be a time-based synchronize deferring to make it minimize the number of rebalances.

Instead, you may want to look into a `cooperative.sticky` rebalance strategy that is much more stable.

> but we may also just bite the bullet and move to Karafka instead

You are more than welcome, and I would be happy to assist. At least a few projects moved from Phobos or Racecar, meaning there are people other than myself in Karafka slack who can assist or potentially answer some questions.

> Which is something we are considering (in which case we'd probably fork it to a new project),

Not easy ;) been there, done that and I am still fixing bugs and shipping improvements to rdkafka-ruby and karafka. It is a never ending stream of updates. Even yesterday I found that logger in rdkafka-ruby completely breaks on forks :sweat_smile: 

Forks are actually last piece of the puzzle and I have them almost done in v1 (static).

@krobitaille-stash in order to minimize number of rebalances you could as said use `cooperative.sticky` + static group memberships with static pod names. This could in theory minimize the rebalances to zero (absolute zero) on stable deployments.

**Comment by dorner** [comment]
@mensfeld Thanks for the correction - I didn't actually go in and check 😅 

I think the benefits and ecosystem of Karafka would *probably* outweigh the pain of the move on our side. We're actually more interested in porting [Deimos](https://github.com/flipp-oss/deimos) (which is a fairly heavyweight framework currently built on top of Phobos). I think after a very brief look at the docs that *most* things should be able to port over... it'll be a decent-sized project.

**Comment by krobitaille-stash** [comment]
@mensfeld Wouldn't we lose the benefits of EKS's pod reallocation and scaling capabilities if we tried to force the static group memberships with static pod names?  I think you're probably right in that on our current iteration on Fargate where our tasks are very static, we don't run into this because we aren't seeing the pods be updated and therefore force rebalances.

Would there still be benefit in moving to `cooperative.sticky` without static pod names and counts?  I'm assuming there wouldn't really be anything to bind to?

Rebalancing itself is ok and makes sense that Kafka and EKS are working well.  It appears the problem is when there is a rebalance in progress from one pod and another pod attempts its own rebalance.  If we can force 1 pod at a time, things seem to be ok.  That is why I was hoping we might be able to add this consumer group join delay.

**Comment by mensfeld** [comment]
Phobos migration should be simple IMHO. Especially if we take into consideration the cost of potential rewrite ;)

> We're actually more interested in porting [Deimos](https://github.com/flipp-oss/deimos) (which is a fairly heavyweight framework currently built on top of Phobos)

I am not extremely fluent in this library though there are things in the karafka ecosystem that Deimos could utilize for enhanced features and capabilities like for example transactional offset management (https://mensfeld.pl/2023/06/inside-kafka-enhancing-data-reliability-through-transactional-offsets-with-karafka/) or transactions for producing out of TOP (https://karafka.io/docs/WaterDrop-Transactions/) + your multi-threaded work seems to align with how Karafka operates. 

Deimos in a way is similar to Karafka Web UI - that is, enhanced "auto injected" capabilities. One company recently released this: https://github.com/BookingSync/dionysus-rb that seems to have some of similar features. That said I would love to have such amazing library as part of the broader Karafka ecosystem and as I stated, I am willing to provide any help I can provide.

> Wouldn't we lose the benefits of EKS's pod reallocation and scaling capabilities if we tried to force the static group memberships with static pod names?

Depends how you configure it. Big topic. Partially yes, partially no.

> It appears the problem is when there is a rebalance in progress from one pod and another pod attempts its own rebalance. If we can force 1 pod at a time, things seem to be ok. That is why I was hoping we might be able to add this consumer group join delay.

cooperative.sticky was created to handle this. It tries to figure out minimum diff of changes needed on a cluster to allocate some work to the new processes. This yield amazing results in regards to rebalances stability.

> Do you know how i'd be able to set this on the broker side?

It's late :sweat: it is one of broker configurations meaning it may require updates to MSK. Not sure if this can be set on a consumer group level.

**Comment by dorner** [comment]
Great to hear - will definitely reach out as we go. Dionysus does seem like it overlaps with a lot of what Deimos does. Deimos has actually been around internally for at least 7 years and is the basis for a lot of our Ruby + Kafka workflow. I feel like over time these kinds of gems tend to expand to very specific use cases called out by the companies and teams that use them. It probably could use some paring down tbh. And I would love to rename some of the features that are in there... maybe a version 3 would be a great opportunity to do that 😁

**Comment by mensfeld** [comment]
> I feel like over time these kinds of gems tend to expand to very specific use cases called out by the companies and teams that use them.

Tell me about it. The whole reason the Karafka ecosystem was able to grow that fast and far is that I finally (2-3 years ago) was able to get a decent number of companies to cooperate with me and share their use cases that did not match mine.

> It probably could use some paring down tbh

You know where to find me (and if not: http://slack.karafka.io/)

Keep me posted as some of the stuff Deimos stuff I have also have internally. Having a common layer like this makes a lot of sense.

**Comment by dorner** [comment]
Thanks so much for the callout @mensfeld . Will definitely be in touch as we look into options.

Sorry for derailing your issue @krobitaille-stash 😁
