### ISSUE TITLE
Ruby-Kafka parent level settings (connection_timeout, client_id) not being passed into Ruby-Kafka config

### ISSUE THREAD

**Issue by krobitaille-stash** [phobos/phobos#167]
I've got a project where i've tried to increase the connection_timeout beyond the default 10s that exists within Ruby-Kafka.  I've tried setting it both in the phobos.yml file and in code as a configuration hash and each time the project starts up, those values end up as the default values in Ruby-Kafka, not what I'm passing

Other components in the configuration are working fine.  The listeners are all being set up.

Inside my phobos.yml file
```
kafka:
  # identifier for this application
  client_id: test
  # timeout setting for connecting to brokers
  connect_timeout: 30
  # timeout setting for socket connections
  socket_timeout: 30
```

This is then being loaded:
`config = YAML.safe_load(ERB.new(File.read(File.expand_path(configuration_yaml))).result)`

And then Phobos is being started up:
```
Phobos.configure(config.deep_merge(kafka: kafka_config_hash))
```

The end result of my `config.deep_merge(kafka: kafka_config_hash)` is

```
{"logger"=>{"file"=>false, "stdout_json"=>false, "level"=>"debug", "ruby_kafka"=>{"level"=>"debug"}},
 "kafka"=>
  {"client_id"=>"test_client",
   "connect_timeout"=>30,
   "socket_timeout"=>30,
   "seed_brokers"=>"kafka+ssl://kafka-.aivencloud.com:11232",
   "ssl_ca_cert"=>"XXX",
   "ssl_client_cert"=>"XXX",
   "ssl_client_cert_key"=>"XXX"},
 "producer"=>
  {"ack_timeout"=>5,
   "required_acks"=>1,
   "max_retries"=>2,
   "retry_backoff"=>1,
   "max_buffer_size"=>1000,
   "max_buffer_bytesize"=>10000000,
   "compression_codec"=>nil,
   "compression_threshold"=>1,
   "max_queue_size"=>1000,
   "delivery_threshold"=>0,
   "delivery_interval"=>0},
 "consumer"=>{"session_timeout"=>90, "offset_commit_interval"=>10, "offset_commit_threshold"=>0, "offset_retention_time"=>nil, "heartbeat_interval"=>30},
 "backoff"=>{"min_ms"=>10000, "max_ms"=>600000},
 "listeners"=>
  [{"handler"=>"Listeners::Test",
    "topic"=>"XXX",
    "group_id"=>"XXX",
    "max_concurrency"=>1,
    "start_from_beginning"=>false,
    "max_bytes_per_partition"=>524288,
    "min_bytes"=>1,
    "max_wait_time"=>5,
    "force_encoding"=>nil,
    "delivery"=>"message"},
]}
```

However when my listeners all start up, I'm getting the default Ruby-Kafka client id and connection timeout.  Not the values i'm setting.  I know parts of the configuration are making it in fine, all my listeners are being set up correctly.  But the values in side the `kafka` block don't seem to be passed all the way to Ruby-Kafka and therefore it uses the defaults.

Do I have something set up incorrectly?  Or is there an issue with that block of configurations not being passed to Ruby-Kafka and therefore it using its defaults?

**Comment by dorner** [comment]
Is there something happening here maybe? [https://github.com/phobos/phobos/blob/master/lib/phobos.rb#L73](https://github.com/phobos/phobos/blob/master/lib/phobos.rb#L73) Is there something in `consumer.kafka` in the config that's overriding it?

You might have to set this up in the `consumer -> kafka` part of the config instead of base `kafka`.

**Comment by krobitaille-stash** [comment]
> Is there something happening here maybe? https://github.com/phobos/phobos/blob/master/lib/phobos.rb#L73 Is there something in `consumer.kafka` in the config that's overriding it?
> 
> You might have to set this up in the `consumer -> kafka` part of the config instead of base `kafka`.

I do have it on the parent "kafka" block in the yml file.  Also in the config at the bottom of the post it looks like its inside the main parent kafka block.

Here is a larger sample of my yml
```
kafka:
  # identifier for this application
  client_id: test
  # timeout setting for connecting to brokers
  connect_timeout: 30
  # timeout setting for socket connections
  socket_timeout: 30
  seed_brokers: "kafka+ssl://kafka-XXX.aivencloud.com:XXX"
  ssl_ca_cert: XXX
  ssl_client_cert: XXX
  ssl_client_cert_key: XXX

producer:
  # number of seconds a broker can wait for replicas to acknowledge
  # a write before responding with a timeout
  ack_timeout: 5
  # number of replicas that must acknowledge a write, or `:all`
  # if all in-sync replicas must acknowledge
  required_acks: 1
  # number of retries that should be attempted before giving up sending
  # messages to the cluster. Does not include the original attempt
  max_retries: 2
  # number of seconds to wait between retries
  retry_backoff: 1
  # number of messages allowed in the buffer before new writes will
  # raise {BufferOverflow} exceptions
  max_buffer_size: 1000
  # maximum size of the buffer in bytes. Attempting to produce messages
  # when the buffer reaches this size will result in {BufferOverflow} being raised
  max_buffer_bytesize: 10000000
  # name of the compression codec to use, or nil if no compression should be performed.
  # Valid codecs: `:snappy` and `:gzip`
  compression_codec:
  # number of messages that needs to be in a message set before it should be compressed.
  # Note that message sets are per-partition rather than per-topic or per-producer
  compression_threshold: 1
  # maximum number of messages allowed in the queue. Only used for async_producer
  max_queue_size: 1000
  # if greater than zero, the number of buffered messages that will automatically
  # trigger a delivery. Only used for async_producer
  delivery_threshold: 0
  # if greater than zero, the number of seconds between automatic message
  # deliveries. Only used for async_producer
  delivery_interval: 0

consumer:
  # number of seconds after which, if a client hasn't contacted the Kafka cluster,
  # it will be kicked out of the group
  session_timeout: 90
  # interval between offset commits, in seconds
  offset_commit_interval: 10
  # number of messages that can be processed before their offsets are committed.
  # If zero, offset commits are not triggered by message processing
  offset_commit_threshold: 0
  # the time period that committed offsets will be retained, in seconds. Defaults to the broker setting.
  offset_retention_time:
  # interval between heartbeats; must be less than the session window
  heartbeat_interval: 30
```

**Comment by krobitaille-stash** [comment]
Ok I think I found the issue.  There are actually two `kafka` blocks being added to the configuration being passed in based on the way the file is parsed and the values are merged.  There is both a :kafka key and a "kafka" key in the hash.  The configuration in Ruby-Kafka is then using the last one entered.

**Comment by krobitaille-stash** [comment]
I am closing this.  This was a pure user mistake I'm sorry.  The way the YAML file is being loaded it actually is adding two separate :kafka and "kafka" keys to the configuration map.  The second one is always being used.

I fixed this by parsing the YML file correctly into Ruby symbols by adding `symbolize_names` to the YAML read.
`config = YAML.safe_load(ERB.new(File.read(File.expand_path(configuration_yaml))).result, symbolize_names: true)`

Thank you for the quick responses I really appreciate it and sorry for the dud issue.

**Comment by dorner** [comment]
Glad you figured it out!
