### ISSUE TITLE
[Question] Why is a new sync producer created each time?

### ISSUE THREAD

**Issue by dorner** [phobos/phobos#95]
Currently, `producer.publish_list` is implemented thusly:
```ruby
        def publish_list(messages)
          client = kafka_client || configure_kafka_client(Phobos.create_kafka_client)
          producer = client.producer(regular_configs)
          produce_messages(producer, messages)
          producer.deliver_messages
        ensure
          producer&.shutdown
        end
```
Is there a reason a new producer is created each time? Why not use the same method as the async producer (put it in the thread store)? There is a connection penalty for creating a producer. In addition, I'm particularly looking at transactions, which aren't really possible across different producers.

**Comment by klippx** [comment]
The main difference (clarifying for the audience here) in the current implementation is that in the case of `publish_list` we do put the `Kafka::Client` itself in the thread store, but in `async_publish_list` we cache the `Kafka::AsyncProducer`. So whenever a call to `publish_list` is made we create a new `Kafka::Producer`, deliver the messages, and shut down the producer (discarding it).

The reason for this is convenience and simplicity more than anything else. 

As per documentation:

> There are two flavors of producers: __regular__ producers and __async__ producers.
>
> Regular producers will deliver the messages synchronously and disconnect, it doesn't matter if you use `publish` or `publish_list` after the messages get delivered the producer will disconnect.
>
> Async producers will accept your messages without blocking, use the methods `async_publish` 
and `async_publish_list` to use async producers.

There is no reason other than simplicity to do it this way, and there is no reason blocking us from caching `Kafka::Producer` instead (and removing the `ensure` block, among other changes).

If we were to change this, I can see that we might gain something in terms of performance (connecting and disconnecting). 
Potential drawbacks with this is we need to introduce a `sync_producer_shutdown` method which has to be called by the user to safely shutdown the producers. This also means that we have to change of documentation for this API, which in turn mean that we _sort of_ are changing a 2 years old+ contract (which might need a major version bump, future compatibility warning messages for using `publish` and `publish_list`). 
All of which, in the end, steals away a part of the simplicity of this API by introducing a _slight_ overhead/gotcha previously only necessary for async version.

It sounds like I'm saying it is not worth it, but no, on the contrary I am open to discussing this further. Especially from your transactions point of view, or from a more "coherent" behaviour across the options we offer for producing, unified code etc. 

But let me start by asking __do you think using the async_producer API instead would a viable option for use cases where performance is a concern over simplicity?__

**Comment by dorner** [comment]
@klippx thanks for your reply! 

It's actually not the performance I'm concerned about - it's solely the possibility of transactions that I'm exploring. My use case is that I have data in a MySQL database and I use Kafka to as a way to "copy" that data to a shared store (Kafka) that other systems can ingest from. If I send a Kafka message inside a DB transaction and then that transaction is aborted, there is no way to get the Kafka message back "out".

Async producers aren't usually my choice because there's more of a chance that something could go wrong with the message and I won't find out.

A method whereby we basically tie a Kafka transaction to a DB transaction should solve the problem (in 99% of the cases) by allowing us to send messages in the middle of a transaction and then commit both transactions at the same time.

**Comment by klippx** [comment]
You are talking about transactional producer introduced in ruby kafka in https://github.com/zendesk/ruby-kafka/pull/608 to be clear? 

Oh, I think I see the issue now... The thing that determines whether a producer is transactional or not is via the configuration, it is enough to say `transactional: true`. So it is possible to set the Phobos producer config to true, which gives you "transactional" style producer in RubyKafka. And that should not work well at all!

So, I am not sure if we should change `publish_list` because it is very clear that it will produce the messages immediately. But, I am sure we need to do _something_ to provide a better user experience when working with Kafka transactions.

Can you show some pseudo code describing the issue? This could be helpful for the discussion to determine the approach going forward. 

I think we need to create a new `transactional_publish` family of functions for Phobos producer making it convenient to produce a message and aborting/commiting by extending the PublicAPI. 

And I also think we need to make sure you do not "accidentaly" create a transactional producer for a "regular" phobos producer (i.e. rejecting transactional config, similar to rejecting async config for the "regular" producer).

**Comment by dorner** [comment]
Hm... we might even want to introduce a new TransactionalProducer class to handle this to make it different.

Something like:
```
class MyProducer
  include Phobos::TransactionalProducer
  ...
end
```
You can look at the ruby-kafka PR for how this might work (block and non-block syntax): https://github.com/zendesk/ruby-kafka/pull/608
The only thing I can see us adding is automatically calling `init_transaction` and `deliver_messages`.

**Comment by dorner** [comment]
Btw, if we're considering a major version bump I'd also want to look at a true batch process method:
```
class MyConsumer
  include Phobos::Consumer
  def consume_batch(payloads)
    # work with an entire batch of payloads at once, e.g. mass insert into the database
  end
end
```
That would be a good opportunity for us to introduce that :)

**Comment by klippx** [comment]
So, the second idea seems like a separate issue/story that we could work out together, you can create a new issue for that 👍🏼

So the conclusion from this discussion is that it would still be useful from your point of view to cache the producer instead of caching the client? We could go for that idea.

**Comment by dorner** [comment]
Yep, for sure, on both points :)

**Comment by klippx** [comment]
So the second idea was merged in #101 

But the first idea remains. To recap, I suggested

> Can you show some pseudo code describing the issue? This could be helpful for the discussion to determine the approach going forward.
> I think we need to create a new transactional_publish family of functions for Phobos producer making it convenient to produce a message and aborting/commiting by extending the PublicAPI.

But then you mentioned that this code wasn't production ready from ruby-kafka point of view.

So should we close this issue? If not, I can help with suggesting how to go forward with an implementation if you want, but I don't think I can dedicate much coding time into it.

**Comment by dorner** [comment]
@klippx I think the transaction parts can be put on hold for now until I hear otherwise from the ruby-kafka people. I also no longer have the use case I originally had for it, so it's not urgent for me.

I do think that caching the sync producer does make sense as it cuts down on the build up / tear down time, as well as making the code follow a single path instead of two. I can look at doing a PR for that at some point.

Re calling shutdown - have you thought of using `at_exit` to do this? The only case I can think of where this wouldn't be sufficient would be if one of the existing threads (main or consumer) created a new thread which then used a producer. But that could be a use case called out in the documentation as requiring manual shutdown.

**Comment by klippx** [comment]
Some cases that trigger shut down:
- Receiving SIGINT, SIGQUIT, SIGTERM when using Phobos CLI
- `at_exit { executor.stop }` when starting executor manually 

In fact, we are using the latter option in our config.ru and starting our consumers using rackup.

**Comment by dorner** [comment]
Those shut down the consumers, though, not the producer, correct? That has to happen manually. Just wondering why we don't shut down the cached async producer on shutdown right now.

**Comment by dorner** [comment]
Don't think there is any remaining discussion or action items here.
