### ISSUE TITLE
Phobos produce: config is nil in create_kafka_client

### ISSUE THREAD

**Issue by afinne** [phobos/phobos#96]
When trying to create a standalone producer, `phobos start` fails due to `config` being `nil` in `create_kafka_client` in `phobos.rb`.

I'm using the approach under the section "Producing messages to Kafka" in the readme.

The code I use to test in `phobos.boot` is:
```
class PostCustomerUpdate
  include Phobos::Producer
end

PostCustomerUpdate.producer.publish('customer.updates', 'payload')
```

I'm doing `bundle exec phobos start` to run this. I am probably doing something wrong, but I tried to follow the documentation.

**Comment by klippx** [comment]
So, config has not been loaded for some reason, and `config` would only be nil if `Phobos.configure(config_file)` has not run. If you look at `Phobos::CLI::Start`, you see this is supposed to happen in `#execute`.

What is command you use to start? 

If you specify a config file and it does not seem to load it, you could always `bundle open phobos` and put a breakpoint or add puts statements to help you debug.

Most likely it is some mistake somewhere that is hard to figure out until you debug it 😎
